
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-java-algo-test using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=encrypt_282c729c38
ROOST_METHOD_SIG_HASH=encrypt_752782d5af

Scenario 1: Encrypting a simple pair of characters in the same row

Details:
  TestName: encryptSameRowCharacters
  Description: This test checks the encryption of two characters that are in the same row of the matrix. The method should replace each character with the one immediately to its right, wrapping around if necessary.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing characters in the same row.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that the characters are encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles characters in the same row by shifting them to the right and wrapping around as needed. This is a fundamental aspect of the Playfair cipher algorithm.

Scenario 2: Encrypting a simple pair of characters in the same column

Details:
  TestName: encryptSameColumnCharacters
  Description: This test checks the encryption of two characters that are in the same column of the matrix. The method should replace each character with the one immediately below it, wrapping around if necessary.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing characters in the same column.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that the characters are encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles characters in the same column by shifting them downwards and wrapping around as needed. This is another fundamental aspect of the Playfair cipher algorithm.

Scenario 3: Encrypting a pair of characters forming a rectangle

Details:
  TestName: encryptRectangleCharacters
  Description: This test checks the encryption of two characters that form a rectangle with the matrix. The method should replace each character with the one at the opposite corner of the rectangle.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing characters forming a rectangle.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that the characters are encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles characters forming a rectangle by swapping them with the characters at the opposite corners. This is a key part of the Playfair cipher algorithm.

Scenario 4: Encrypting plaintext with repeated characters

Details:
  TestName: encryptWithRepeatedCharacters
  Description: This test checks the encryption of plaintext containing repeated characters. The method should handle repeated characters by inserting an 'X' between them.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing repeated characters.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that the repeated characters are handled correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles repeated characters by inserting an 'X' between them. This is necessary to maintain the two-character pair structure required by the Playfair cipher.

Scenario 5: Encrypting plaintext with 'J' character

Details:
  TestName: encryptWithJCharacter
  Description: This test checks the encryption of plaintext containing the character 'J'. The method should replace 'J' with 'I' before encryption.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing the character 'J'.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that the 'J' character is replaced with 'I' and encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles the character 'J' by replacing it with 'I' before encryption. This is a specific rule of the Playfair cipher.

Scenario 6: Encrypting plaintext with odd number of characters

Details:
  TestName: encryptWithOddNumberOfCharacters
  Description: This test checks the encryption of plaintext with an odd number of characters. The method should append an 'X' to the end of the plaintext to make it even.
Execution:
  Arrange: Initialize the matrix with a key and plaintext with an odd number of characters.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that an 'X' is appended to the plaintext and encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles plaintext with an odd number of characters by appending an 'X' to make it even. This is necessary to maintain the two-character pair structure required by the Playfair cipher.

Scenario 7: Encrypting plaintext with special characters

Details:
  TestName: encryptWithSpecialCharacters
  Description: This test checks the encryption of plaintext containing special characters. The method should remove special characters before encryption.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing special characters.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that special characters are removed and the remaining text is encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles special characters by removing them before encryption. This is necessary to maintain the alphabetical structure required by the Playfair cipher.

Scenario 8: Encrypting plaintext with uppercase and lowercase characters

Details:
  TestName: encryptWithMixedCaseCharacters
  Description: This test checks the encryption of plaintext containing both uppercase and lowercase characters. The method should convert all characters to uppercase before encryption.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing mixed case characters.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that all characters are converted to uppercase and encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles mixed case characters by converting them to uppercase before encryption. This is necessary to maintain the uniform structure required by the Playfair cipher.

Scenario 9: Encrypting plaintext with spaces

Details:
  TestName: encryptWithSpaces
  Description: This test checks the encryption of plaintext containing spaces. The method should remove spaces before encryption.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing spaces.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that spaces are removed and the remaining text is encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles spaces by removing them before encryption. This is necessary to maintain the alphabetical structure required by the Playfair cipher.

Scenario 10: Encrypting plaintext with numbers

Details:
  TestName: encryptWithNumbers
  Description: This test checks the encryption of plaintext containing numbers. The method should remove numbers before encryption.
Execution:
  Arrange: Initialize the matrix with a key and plaintext containing numbers.
  Act: Call the encrypt method with the prepared plaintext.
  Assert: Verify that numbers are removed and the remaining text is encrypted correctly by checking the output.
Validation:
  This test ensures that the encryption process correctly handles numbers by removing them before encryption. This is necessary to maintain the alphabetical structure required by the Playfair cipher.

*/

// ********RoostGPT********

package com.thealgorithms.ciphers;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;

public class PlayfairCipherEncryptTest {

	private PlayfairCipher playfairCipher;

	@BeforeEach
	public void setUp() {
		// TODO: Change the key value as per the test case
		playfairCipher = new PlayfairCipher("KEYWORD");
	}

	@Tag("valid")
	@Test
	public void testEncryptSameRowCharacters() {
		String plaintext = "HELLO";
		String expectedCiphertext = "IFMMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptSameColumnCharacters() {
		String plaintext = "ABBA";
		String expectedCiphertext = "KCKC";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptRectangleCharacters() {
		String plaintext = "HILL";
		String expectedCiphertext = "IFMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptWithRepeatedCharacters() {
		String plaintext = "HELLO";
		String expectedCiphertext = "IFMMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptWithJCharacter() {
		String plaintext = "JELLO";
		String expectedCiphertext = "IFMMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptWithOddNumberOfCharacters() {
		String plaintext = "HELLOX";
		String expectedCiphertext = "IFMMPX";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptWithSpecialCharacters() {
		String plaintext = "HELLO@";
		String expectedCiphertext = "IFMMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptWithMixedCaseCharacters() {
		String plaintext = "HeLLo";
		String expectedCiphertext = "IFMMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptWithSpaces() {
		String plaintext = "HE LLO";
		String expectedCiphertext = "IFMMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Tag("valid")
	@Test
	public void testEncryptWithNumbers() {
		String plaintext = "HELLO1";
		String expectedCiphertext = "IFMMP";
		String actualCiphertext = playfairCipher.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

}