
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-java-algo-test using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=encrypt_f7ab1f7114
ROOST_METHOD_SIG_HASH=encrypt_6cda6a04c6

Scenario 1: Encrypt a single character

Details:
  TestName: encryptSingleCharacter
  Description: This test checks if the encrypt method correctly encrypts a single character from the plaintext.
Execution:
  Arrange: Prepare a single character string.
  Act: Call the encrypt method with the single character string.
  Assert: Verify that the returned ciphertext matches the expected coordinates.
Validation:
  This test ensures that the method correctly maps a single character to its corresponding coordinates in the Polybius square.

Scenario 2: Encrypt a string with multiple characters

Details:
  TestName: encryptMultipleCharacters
  Description: This test verifies that the encrypt method correctly encrypts a string containing multiple characters.
Execution:
  Arrange: Prepare a string with multiple characters.
  Act: Call the encrypt method with the string.
  Assert: Verify that the returned ciphertext matches the expected concatenated coordinates.
Validation:
  This test checks the method's ability to handle multiple characters and ensure correct concatenation of coordinates.

Scenario 3: Encrypt a string with mixed case characters

Details:
  TestName: encryptMixedCaseCharacters
  Description: This test ensures that the encrypt method correctly handles mixed case characters by converting them to uppercase.
Execution:
  Arrange: Prepare a string with mixed case characters.
  Act: Call the encrypt method with the string.
  Assert: Verify that the returned ciphertext matches the expected coordinates for the uppercase characters.
Validation:
  This test confirms that the method correctly converts lowercase characters to uppercase before encryption.

Scenario 4: Encrypt a string with special characters

Details:
  TestName: encryptWithSpecialCharacters
  Description: This test checks how the encrypt method handles special characters that are not part of the Polybius square.
Execution:
  Arrange: Prepare a string containing special characters.
  Act: Call the encrypt method with the string.
  Assert: Verify that the method throws an appropriate exception or handles the special characters gracefully.
Validation:
  This test ensures that the method can handle unexpected input gracefully without crashing.

Scenario 5: Encrypt an empty string

Details:
  TestName: encryptEmptyString
  Description: This test verifies that the encrypt method correctly handles an empty string input.
Execution:
  Arrange: Prepare an empty string.
  Act: Call the encrypt method with the empty string.
  Assert: Verify that the returned ciphertext is an empty string.
Validation:
  This test confirms that the method does not fail and returns an empty string when given an empty input.

Scenario 6: Encrypt a string with only spaces

Details:
  TestName: encryptStringWithSpaces
  Description: This test checks how the encrypt method handles a string consisting only of spaces.
Execution:
  Arrange: Prepare a string with only spaces.
  Act: Call the encrypt method with the string.
  Assert: Verify that the returned ciphertext is an empty string or handles spaces appropriately.
Validation:
  This test ensures that the method correctly ignores spaces or handles them as expected.

Scenario 7: Encrypt a string with non-alphabetic characters

Details:
  TestName: encryptStringWithNonAlphabeticCharacters
  Description: This test verifies that the encrypt method correctly handles non-alphabetic characters by ignoring them.
Execution:
  Arrange: Prepare a string with non-alphabetic characters.
  Act: Call the encrypt method with the string.
  Assert: Verify that the returned ciphertext matches the expected coordinates for the alphabetic characters only.
Validation:
  This test confirms that the method correctly filters out non-alphabetic characters before encryption.

Scenario 8: Encrypt a string with characters outside the Polybius square

Details:
  TestName: encryptCharactersOutsidePolybiusSquare
  Description: This test checks how the encrypt method handles characters that are not part of the Polybius square.
Execution:
  Arrange: Prepare a string with characters outside the Polybius square.
  Act: Call the encrypt method with the string.
  Assert: Verify that the method throws an appropriate exception or handles the characters gracefully.
Validation:
  This test ensures that the method can handle characters outside the Polybius square without crashing.

Scenario 9: Encrypt a string with repeated characters

Details:
  TestName: encryptStringWithRepeatedCharacters
  Description: This test verifies that the encrypt method correctly handles repeated characters in the plaintext.
Execution:
  Arrange: Prepare a string with repeated characters.
  Act: Call the encrypt method with the string.
  Assert: Verify that the returned ciphertext matches the expected concatenated coordinates for each character.
Validation:
  This test confirms that the method correctly encrypts repeated characters without any issues.

Scenario 10: Encrypt a long string

Details:
  TestName: encryptLongString
  Description: This test checks how the encrypt method performs with a long string input.
Execution:
  Arrange: Prepare a long string.
  Act: Call the encrypt method with the long string.
  Assert: Verify that the returned ciphertext matches the expected concatenated coordinates.
Validation:
  This test ensures that the method can handle long strings efficiently without performance issues.

*/

// ********RoostGPT********

package com.thealgorithms.ciphers;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;

public class PolybiusEncryptTest {

	@Test
	@Tag("valid")
	public void encryptSingleCharacter() {
		String plaintext = "A";
		String expectedCiphertext = "11";
		String actualCiphertext = Polybius.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Test
	@Tag("valid")
	public void encryptMultipleCharacters() {
		String plaintext = "HELLO";
		String expectedCiphertext = "2351121212";
		String actualCiphertext = Polybius.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Test
	@Tag("valid")
	public void encryptMixedCaseCharacters() {
		String plaintext = "HeLlO";
		String expectedCiphertext = "2351121212";
		String actualCiphertext = Polybius.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Test
	@Tag("invalid")
	public void encryptWithSpecialCharacters() {
		String plaintext = "HELLO!";
		assertThrows(IllegalArgumentException.class, () -> Polybius.encrypt(plaintext));
	}

	@Test
	@Tag("valid")
	public void encryptEmptyString() {
		String plaintext = "";
		String expectedCiphertext = "";
		String actualCiphertext = Polybius.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Test
	@Tag("valid")
	public void encryptStringWithSpaces() {
		String plaintext = "HE LLO";
		String expectedCiphertext = "2351121212";
		String actualCiphertext = Polybius.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Test
	@Tag("invalid")
	public void encryptStringWithNonAlphabeticCharacters() {
		String plaintext = "HELLO123";
		assertThrows(IllegalArgumentException.class, () -> Polybius.encrypt(plaintext));
	}

	@Test
	@Tag("invalid")
	public void encryptCharactersOutsidePolybiusSquare() {
		String plaintext = "HELLOJ";
		assertThrows(IllegalArgumentException.class, () -> Polybius.encrypt(plaintext));
	}

	@Test
	@Tag("valid")
	public void encryptStringWithRepeatedCharacters() {
		String plaintext = "HELLOOO";
		String expectedCiphertext = "23511212121212";
		String actualCiphertext = Polybius.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

	@Test
	@Tag("valid")
	public void encryptLongString() {
		String plaintext = "HELLOHELLOHELLOHELLOHELLO";
		String expectedCiphertext = "23511212122351121212235112121223511212122351121212";
		String actualCiphertext = Polybius.encrypt(plaintext);
		assertEquals(expectedCiphertext, actualCiphertext);
	}

}