
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-java-algo-test using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=encrypt_2fa104da27
ROOST_METHOD_SIG_HASH=encrypt_3045562d7b

Scenario 1: Encrypting a simple message with a simple key

Details:
  TestName: encryptSimpleMessageSimpleKey
  Description: This test checks the basic functionality of the encrypt method by encrypting a simple message using a simple key. It verifies that the method correctly shifts each character according to the key.
Execution:
  Arrange: Prepare a simple message "HELLO" and a simple key "KEY".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "RIJVS".
Validation:
  The assertion aims to verify that the method correctly encrypts each letter of the message by shifting it according to the corresponding letter in the key. This test ensures the basic encryption functionality is working as expected.

Scenario 2: Encrypting a message with a key longer than the message

Details:
  TestName: encryptMessageWithLongerKey
  Description: This test checks the behavior of the encrypt method when the key is longer than the message. It verifies that the method correctly wraps around the key to encrypt the message.
Execution:
  Arrange: Prepare a message "HELLO" and a key "KEYS".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "RIJVS".
Validation:
  The assertion aims to verify that the method correctly handles keys longer than the message by wrapping around the key. This test ensures the method does not throw an error and correctly encrypts the message.

Scenario 3: Encrypting a message with a key shorter than the message

Details:
  TestName: encryptMessageWithShorterKey
  Description: This test checks the behavior of the encrypt method when the key is shorter than the message. It verifies that the method correctly repeats the key to encrypt the entire message.
Execution:
  Arrange: Prepare a message "HELLO" and a key "K".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "HIFMP".
Validation:
  The assertion aims to verify that the method correctly repeats the key to encrypt the entire message. This test ensures the method handles keys shorter than the message correctly.

Scenario 4: Encrypting a message with non-alphabetic characters

Details:
  TestName: encryptMessageWithNonAlphabeticCharacters
  Description: This test checks the behavior of the encrypt method when the message contains non-alphabetic characters. It verifies that the method correctly encrypts only the alphabetic characters and leaves non-alphabetic characters unchanged.
Execution:
  Arrange: Prepare a message "HELLO 123" and a key "KEY".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "RIJVS 123".
Validation:
  The assertion aims to verify that the method correctly encrypts only the alphabetic characters and leaves non-alphabetic characters unchanged. This test ensures the method handles mixed content correctly.

Scenario 5: Encrypting a message with mixed case characters

Details:
  TestName: encryptMessageWithMixedCaseCharacters
  Description: This test checks the behavior of the encrypt method when the message contains mixed case characters. It verifies that the method correctly encrypts both uppercase and lowercase characters.
Execution:
  Arrange: Prepare a message "Hello" and a key "Key".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "Rijvs".
Validation:
  The assertion aims to verify that the method correctly encrypts both uppercase and lowercase characters. This test ensures the method handles mixed case input correctly.

Scenario 6: Encrypting an empty message

Details:
  TestName: encryptEmptyMessage
  Description: This test checks the behavior of the encrypt method when the message is empty. It verifies that the method returns an empty string.
Execution:
  Arrange: Prepare an empty message "" and a key "KEY".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "".
Validation:
  The assertion aims to verify that the method correctly handles an empty message by returning an empty string. This test ensures the method does not throw an error for an empty input.

Scenario 7: Encrypting a message with an empty key

Details:
  TestName: encryptMessageWithEmptyKey
  Description: This test checks the behavior of the encrypt method when the key is empty. It verifies that the method returns the original message unchanged.
Execution:
  Arrange: Prepare a message "HELLO" and an empty key "".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "HELLO".
Validation:
  The assertion aims to verify that the method correctly handles an empty key by returning the original message unchanged. This test ensures the method does not throw an error for an empty key.

Scenario 8: Encrypting a message with a key containing non-alphabetic characters

Details:
  TestName: encryptMessageWithKeyContainingNonAlphabeticCharacters
  Description: This test checks the behavior of the encrypt method when the key contains non-alphabetic characters. It verifies that the method ignores non-alphabetic characters in the key.
Execution:
  Arrange: Prepare a message "HELLO" and a key "K3Y".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "RIJVS".
Validation:
  The assertion aims to verify that the method correctly ignores non-alphabetic characters in the key. This test ensures the method handles keys with mixed content correctly.

Scenario 9: Encrypting a message with a key containing mixed case characters

Details:
  TestName: encryptMessageWithKeyContainingMixedCaseCharacters
  Description: This test checks the behavior of the encrypt method when the key contains mixed case characters. It verifies that the method correctly handles mixed case characters in the key.
Execution:
  Arrange: Prepare a message "HELLO" and a key "KeY".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "RIJVS".
Validation:
  The assertion aims to verify that the method correctly handles mixed case characters in the key. This test ensures the method processes the key correctly regardless of its case.

Scenario 10: Encrypting a message with a key containing only non-alphabetic characters

Details:
  TestName: encryptMessageWithKeyContainingOnlyNonAlphabeticCharacters
  Description: This test checks the behavior of the encrypt method when the key contains only non-alphabetic characters. It verifies that the method returns the original message unchanged.
Execution:
  Arrange: Prepare a message "HELLO" and a key "123".
  Act: Call the encrypt method with the prepared message and key.
  Assert: Verify that the returned string is "HELLO".
Validation:
  The assertion aims to verify that the method correctly handles keys containing only non-alphabetic characters by returning the original message unchanged. This test ensures the method does not throw an error for such keys.

*/

// ********RoostGPT********

package com.thealgorithms.ciphers;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;

public class VigenereEncryptTest {

	private final Vigenere vigenere = new Vigenere();

	@Test
	@Tag("valid")
	public void testEncryptSimpleMessageSimpleKey() {
		String message = "HELLO";
		String key = "KEY";
		String expected = "RIJVS";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithLongerKey() {
		String message = "HELLO";
		String key = "KEYS";
		String expected = "RIJVS";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithShorterKey() {
		String message = "HELLO";
		String key = "K";
		String expected = "HIFMP";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithNonAlphabeticCharacters() {
		String message = "HELLO 123";
		String key = "KEY";
		String expected = "RIJVS 123";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithMixedCaseCharacters() {
		String message = "Hello";
		String key = "Key";
		String expected = "Rijvs";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptEmptyMessage() {
		String message = "";
		String key = "KEY";
		String expected = "";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithEmptyKey() {
		String message = "HELLO";
		String key = "";
		String expected = "HELLO";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithKeyContainingNonAlphabeticCharacters() {
		String message = "HELLO";
		String key = "K3Y";
		String expected = "RIJVS";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithKeyContainingMixedCaseCharacters() {
		String message = "HELLO";
		String key = "KeY";
		String expected = "RIJVS";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

	@Test
	@Tag("valid")
	public void testEncryptMessageWithKeyContainingOnlyNonAlphabeticCharacters() {
		String message = "HELLO";
		String key = "123";
		String expected = "HELLO";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual);
	}

}