
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-java-algo-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=encrypt_2fa104da27
ROOST_METHOD_SIG_HASH=encrypt_3045562d7b


Scenario 1: Encrypt a message containing only lowercase letters

Details:
  TestName: encryptLowercaseMessage
  Description: Validate that the `encrypt` method correctly encrypts a straightforward message containing only lowercase letters using the provided key. This tests the logic of handling lowercase characters.

Execution:
  Arrange: Prepare a message with lowercase letters, e.g., "hello", and a key such as "key".
  Act: Call the `encrypt` method with the given message and key.
  Assert: Use JUnit assertions to verify the returned result matches the expected encrypted output.

Validation:
  Ensure the logic for processing lowercase letters and incorporating the key is functioning as intended. This verifies the core functionality of character manipulation in the method for lowercase handling.

---

Scenario 2: Encrypt a message containing only uppercase letters

Details:
  TestName: encryptUppercaseMessage
  Description: Test that the `encrypt` method accurately encrypts a message composed exclusively of uppercase letters, validating the method's handling of uppercase characters.

Execution:
  Arrange: Create a message with uppercase letters, e.g., "HELLO", and a key, e.g., "KEY".
  Act: Call the `encrypt` method with the provided message and key.
  Assert: Use JUnit assertions to verify the returned output matches the expected encrypted result.

Validation:
  Confirm that the logic for handling uppercase characters and applying the key works correctly, validating correct ASCII manipulation for uppercase letters.

---

Scenario 3: Encrypt a message containing mixed case letters

Details:
  TestName: encryptMixedCaseMessage
  Description: Validate that the `encrypt` method properly encrypts a message that contains both uppercase and lowercase letters, ensuring case-sensitive encryption.

Execution:
  Arrange: Prepare a mixed case message, e.g., "HelloWorld", and a key, e.g., "Key".
  Act: Call the `encrypt` method with the specified message and key.
  Assert: Use JUnit assertions to compare the output with the expected encrypted result, accounting for case sensitivity.

Validation:
  Verify that the method retains the uppercase and lowercase formatting in the encrypted output while applying the key. This ensures case handling logic is functional.

---

Scenario 4: Encrypt a message containing non-letter characters

Details:
  TestName: encryptMessageWithNonLetters
  Description: Validate the method's behavior when non-letter characters are included in the message, ensuring they remain unchanged in the encrypted output.

Execution:
  Arrange: Prepare a message with mixed letters and non-letters, e.g., "Hello, World!" and a key, e.g., "Key".
  Act: Call the `encrypt` method with the message and key.
  Assert: Use JUnit assertions to verify non-letter characters remain unmodified in the encrypted output.

Validation:
  Ensure the method explicitly excludes non-letter characters from encryption processing while correctly modifying letters.

---

Scenario 5: Encrypt a blank message

Details:
  TestName: encryptBlankMessage
  Description: Test the `encrypt` method's behavior when given an empty string as the message, validating edge case handling for empty inputs.

Execution:
  Arrange: Pass an empty string as the message, e.g., "", with any valid key, e.g., "Key".
  Act: Call the `encrypt` method.
  Assert: Verify that the output is an empty string.

Validation:
  Confirm the method gracefully handles empty input without throwing errors or incorrectly processing it.

---

Scenario 6: Encrypt a single character message

Details:
  TestName: encryptSingleCharacterMessage
  Description: Validate the `encrypt` method's functionality when the message contains only a single character, testing edge cases for minimal input.

Execution:
  Arrange: Use a single character message, e.g., "H", and a simple key, e.g., "Key".
  Act: Call the `encrypt` method with the parameters.
  Assert: Verify that the output matches the expected encrypted result.

Validation:
  Ensure the method correctly encrypts single-character input without errors or anomalies in output.

---

Scenario 7: Encrypt with a key longer than the message

Details:
  TestName: encryptKeyLongerThanMessage
  Description: Validate the method's handling when the key is longer than the message, ensuring the extra key characters are ignored.

Execution:
  Arrange: Use a message, e.g., "Hi", and a longer key, e.g., "LongKey".
  Act: Call the `encrypt` method with the inputs.
  Assert: Verify the output against the expected encrypted result.

Validation:
  Ensure the method correctly cyclically processes the key, focusing only on the relevant portions matching the message length.

---

Scenario 8: Encrypt with a key shorter than the message

Details:
  TestName: encryptKeyShorterThanMessage
  Description: Validate the method properly reuses the key cyclically when the key is shorter than the message, ensuring correct application of the encryption algorithm.

Execution:
  Arrange: Use a message, e.g., "LongMessage", and a shorter key, e.g., "Key".
  Act: Call the `encrypt` method with these values.
  Assert: Compare the output with the expected cyclically encrypted result.

Validation:
  Verify that the method correctly cycles through the key to ensure all characters of the message are encrypted.

---

Scenario 9: Encrypt using a key with mixed case

Details:
  TestName: encryptKeyWithMixedCase
  Description: Validate that the `encrypt` method accurately applies a key containing both uppercase and lowercase letters, ensuring mixed case key processing.

Execution:
  Arrange: Use a message, e.g., "HelloWorld", and a mixed case key, e.g., "KeY".
  Act: Call the `encrypt` method with the inputs.
  Assert: Verify the output matches the expected mixed case encrypted result.

Validation:
  Ensure the method correctly converts the key appropriately for processing, without modifying its original case.

---

Scenario 10: Encrypt a message with special Unicode characters

Details:
  TestName: encryptMessageWithUnicodeCharacters
  Description: Test the handling of special Unicode characters in a message, ensuring non-letter Unicode symbols remain intact and unchanged.

Execution:
  Arrange: Use a message, e.g., "Hello 😊", and a valid key, e.g., "Key".
  Act: Call the `encrypt` method with the given inputs.
  Assert: Verify that Unicode characters remain unchanged in the output.

Validation:
  Confirm the method excludes Unicode characters from encryption logic while handling valid letters appropriately.

*/

// ********RoostGPT********

package com.thealgorithms.ciphers;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;

public class VigenereEncryptTest {

	private final Vigenere vigenere = new Vigenere();

	@Test
	@Tag("valid")
	public void encryptLowercaseMessage() {
		String message = "hello";
		String key = "key";
		String expected = "riyvs";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Encryption did not work as expected for lowercase message");
	}

	@Test
	@Tag("valid")
	public void encryptUppercaseMessage() {
		String message = "HELLO";
		String key = "KEY";
		String expected = "RIYVS";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Encryption did not work as expected for uppercase message");
	}

	@Test
	@Tag("valid")
	public void encryptMixedCaseMessage() {
		String message = "HelloWorld";
		String key = "Key";
		String expected = "RiyvsUosnf";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Encryption did not work as expected for mixed-case message");
	}

	@Test
	@Tag("boundary")
	public void encryptMessageWithNonLetters() {
		String message = "Hello, World!";
		String key = "Key";
		String expected = "Riyvs, Uosnf!";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Non-letter characters were modified incorrectly");
	}

	@Test
	@Tag("boundary")
	public void encryptBlankMessage() {
		String message = "";
		String key = "Key";
		String expected = "";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Encryption did not handle blank message correctly");
	}

	@Test
	@Tag("boundary")
	public void encryptSingleCharacterMessage() {
		String message = "H";
		String key = "Key";
		String expected = "R";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Single-character message encryption failed");
	}

	@Test
	@Tag("valid")
	public void encryptKeyLongerThanMessage() {
		String message = "Hi";
		String key = "LongKey";
		String expected = "Sd";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Key longer than the message was not handled correctly");
	}

	@Test
	@Tag("valid")
	public void encryptKeyShorterThanMessage() {
		String message = "LongMessage";
		String key = "Key";
		String expected = "VgtyWiyvlwc";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Key shorter than the message was not handled correctly");
	}

	@Test
	@Tag("valid")
	public void encryptKeyWithMixedCase() {
		String message = "HelloWorld";
		String key = "KeY";
		String expected = "RiyvsUosnf";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Mixed-case key was not handled correctly");
	}

	@Test
	@Tag("boundary")
	public void encryptMessageWithUnicodeCharacters() {
		String message = "Hello 😊";
		String key = "Key";
		String expected = "Riyvs 😊";
		String actual = vigenere.encrypt(message, key);
		assertEquals(expected, actual, "Unicode characters were modified incorrectly");
	}

}